Pequeños órganos que se encuentran junto a los ganglios linfáticos en la mayoría de los mamíferos. Fueron el primer órgano relacionado con la magia que se descubrió durante el despertar de la magia. Durante mucho tiempo se especuló acerca de sus funciones; hasta que en una de las épocas más violentas tras la aparición de la [Universidad] (https://github.com/Jsevillamol/Brave-New-World/wiki/Universidad) unos magos sin demasiados escrúpulos demostraron que los ganglios actúan como depósitos de partículas taúmicas. 

# ¿Por qué no hay un órgano centralizado de reserva?
En un primer momento se pensó que se debía a los terribles efectos secundarios que puede llegar a tener el acumular en el mismo sitio una cantidad demasiado grande de [taus](https://github.com/Jsevillamol/Brave-New-World/wiki/Tau). Después, durante la era moderna, con el estudio molecular de la biología se descubrió que los linfocitos pueden utilizar las partículas taúmicas para combatir infecciones, por eso se encuentran junto a los ganglios linfáticos. El acceso a las reservas propias es fácil y los agentes infecciosos tendrán que luchar contra las defensas del cuerpo antes de poder acceder a sus reservas mágicas.

# Composición de los ganglios
El mayor avance en el estudio de los ganglios se consiguió durante la [Runavolución](https://github.com/Jsevillamol/Brave-New-World/wiki/Runavoluci%C3%B3n) gracias a la invención de los microscopios aumentados con sigaldría.
Los ganglios están formados mayormente por células sin núcleo llamadas taumocitos. En su interior hay un sistema vacuolar doble conocido como taumoplasto en el que se acumulan las partículas taúmicas atrapadas en una molécula orgánica. Ésta molécula puede romperse mediante el uso de enzimas que también atrapan la partícula táumica que se libera. De esta forma el cuerpo puede aprovechar de forma controlada el uso de la magia. 

Se han encontrado también pequeñas vacuolas en el interior del taumoplasto que contienen grandes concentraciones de la enzima liberadora de [taus](https://github.com/Jsevillamol/Brave-New-World/wiki/Tau). Se cree que esto permite al taumocito suicidarse mediante la liberación de toda la energía mágica en el caso de ser infectado para no permitir al agente infeccioso el acceso a sus reservas.
